### ISSUE TITLE
Includes work with query, but not with /works/{doi} request

### ISSUE THREAD

**Issue by MW3000** [datacite/spinone#13]
When I send a query like:
`https://api.datacite.org/works?query=10.5281/zenodo.35233&include=publisher,resource-type`
The answer includes _publisher_ and _resource type_ information, as expected.

But when I send:
`https://api.datacite.org/works/10.5281/zenodo.35233&include=publisher,resource-type`
I get a 404 answer.

I would like to use include parameters also when asking directly for resources.

**Comment by mfenner** [comment]
Use a question mark (?) instead of an ampersand (&): `https://api.datacite.org/works/10.5281/zenodo.35233?include=publisher,resource-type`.

**Comment by MW3000** [comment]
You are right, of course 👍
