### ISSUE TITLE
error in api documentation and query question

### ISSUE THREAD

**Issue by Bhoft** [datacite/spinone#14]
from the api documentation this url should work
https://api.datacite.org/publisher/{publisher-id}
https://api.datacite.org/publisher/tib.eurescom

But it doesn't work, the correct url is:
https://api.datacite.org/publishers/tib.eurescom

So I guess there is an error in the documentation because all other urls in the section "Resource components and identifiers" are plural (e.g. works, members, work-types).

Why does a wrong URL like below returns a "blank page" with http status 404?
Shouldn't it return an JSONAPI error object with error "wrong route/url" instead?
https://api.datacite.org/publisher/tib.eurescom

So here is my question:
How can I select all works from the Datacenter "tib.eurescom"
and only return those entries where e.g. the [container-title] is set to "reThink Project".  (which is the "publisher" as given in the xml data which sent to datacite)

Of course I could use the "query" parameter, but as this is a full text search which also searches in all field like title etc. it is not really secure that only the wanted items are returned.

My tests so far:
// full text search
https://api.datacite.org/works?publisher-id=tib.eurescom&rows=1000000&query=rethink+project

// doi prefix search (not working returns publisher lists ?)
https://api.datacite.org/works?publisher-id=tib.eurescom&rows=1000000&query=RTH-645342
// doi prefix search (not working returns publisher lists ?)
https://api.datacite.org/works?publisher-id=tib.eurescom&rows=1000000&query=10.18153/RTH-645342

I wonder why on the api the datacenter search parameter is "publisher_id" and on search.datacite.org the parameter names is "datacentere_facet".

e.g.
http://search.datacite.org/api?q=publisher%3A(rethink+project)&fq=datacentre_facet%3A%22TIB.EURESCOM+-+Eurescom+GmbH%22&fl=doi,creator,title,publisher,publicationYear,datacentre&fq=is_active:true&fq=has_metadata:true&rows=10&wt=json&indent=true

Which returns my requested result. But how can I get this through the api.datacite?

I also tried this:
https://api.datacite.org/works?publisher-id=tib.eurescom&rows=1000000&query=title:rethink'
which searches for the title with "rethink" in it.

I tried then to search for the container-title (because this is listed as the attribute name  in each work in the resultset) which doesn't work.
https://api.datacite.org/works?publisher-id=tib.eurescom&rows=1000000&query=container-title:reThink+Project

then I thought maybe use the parameter name of the search site...and viola it works. 
https://api.datacite.org/works?publisher-id=tib.eurescom&rows=1000000&query=publisher:reThink+Project

But how on earth should some developer should get to this URL other then try an error?

Do I miss some documentation?

Kind regards
Benjamin

**Comment by mfenner** [comment]
Thanks Benjamin for the great feedback.

I have fixed the singular/plural error, it will be deployed in a few minutes.

We will launch a documentation site in a few weeks that will provide much better documentation, and that should make it much easier to do the kinds of queries you want to do. Until then, the syntax for queries of specific fields is `fieldName:string`, e.g. https://api.datacite.org/works?query=publisher:%22reThink%20Project%22 or https://api.datacite.org/works?query=publisher%3A(rethink+project), which is basically the same as the old API.

**Comment by Bhoft** [comment]
Hi thanks for your response,
the problem is that it isn't the fieldName at least not in the result.
Because in the result the publisher field is named "container-title".

Don't know if you detected the "bug" which I only mentioned above. 
If I query for something which doesn't return any result I always get a huge list (1000 entries) of publishers in the meta array.
So if nothing is found I will always get the meta information for the first 1000 publishers that there is nothing found  ;) and this also if I only query one specific publisher.
I guess this is a little bit of an overhead if the result is zero the publishers list in the meta array should also be empty.
e.g. https://api.datacite.org/works?publisher-id=tib.eurescom&rows=1000000&query=doi:10.18153/RTH-645342-D1_0
(there isn't an entry available with that doi)


Some other question is there some way to query for multiple DOIs in one query?
And could you also give an example if I want to query for the publisher and e.g. the published year with and "and" / "or" condition?

edit:
OK I guess "or" works like this (just add a new query parameter):
https://api.datacite.org/works?publisher-id=tib.eurescom&rows=1000000&query=publisher:rethink-project&query=doi:10.18153/RTH-645342-D1_1

and "and" condition like this (separate conditions with space (encoded "+") to the same query parameter)
https://api.datacite.org/works?publisher-id=tib.eurescom&rows=1000000&query=publisher:rethink-project+publicationYear%3A%5B2014+TO+2015%5D

Is this correct?

thx in advance.
