### ISSUE TITLE
/works/{doi} retrieval no longer working

### ISSUE THREAD

**Issue by dagrenzer** [datacite/spinone#15]
The form api.datacite.org/works/{doi} used to return metadata for the requested record, but it now gives a 404 - Code: NoSuchKey error. I have found that api.datacite.org/works?query=doi:{doi} returns the equivalent, but the documentation still indicates that api.datacite.org/works/{doi} should work.

**Comment by mfenner** [comment]
This was caused by a misconfigration of our API router, and should again be working as expected.

**Comment by dagrenzer** [comment]
Thanks!
