### ISSUE TITLE
500 Error during pagination with DATS API

### ISSUE THREAD

**Issue by bozyurt** [datacite/spinone#16]
this works
https://api.datacite.org/dats?publisher-id=OSTI.NIMH&offset=3200&rows=100
this gives 500 error
https://api.datacite.org/dats?publisher-id=OSTI.NIMH&offset=3300&rows=100
this works
https://api.datacite.org/dats?publisher-id=OSTI.NIMH&offset=3400&rows=100

**Comment by richardhallett** [comment]
Evaluating this bug again and unable to reproduce, if this is still a problem, please re-open, thanks.
