### ISSUE TITLE
REST API in test show different counts that SOLR API in TEST

### ISSUE THREAD

**Issue by kjgarza** [datacite/spinone#30]
https://search.test.datacite.org/api?&q=*

https://api.test.datacite.org/works

It could be that the REST API is pointing to a different place

**Comment by kjgarza** [comment]
importer might be to problem:

https://search.test.datacite.org/api?&q=has_metadata:true

https://search.test.datacite.org/api?&q=has_metadata:false

**Comment by kjgarza** [comment]
I am unsure this is still holding. the difference is so minimal (100 DOIS today) . Could it be that the index was interrupted? Additionally this bug was brought up during the development of `states` which where added to the index. Maybe this affected back then but now is not the case.

**Comment by kjgarza** [comment]
@richardhallett  please review

**Comment by kjgarza** [comment]
Actually the query the API makes is : https://search.datacite.org/api?q=*%3A*&start=0&rows=25&fl=doi%2Curl%2Ctitle%2Ccreator%2Cdescription%2Cpublisher%2CpublicationYear%2CresourceType%2CresourceTypeGeneral%2CrightsURI%2Cversion%2Cdatacentre_symbol%2Callocator_symbol%2Cschema_version%2Cxml%2Cmedia%2Cminted%2Cupdated%2Cchecked&fq=has_metadata%3Atrue+AND+is_active%3Atrue&facet=true&facet.field=publicationYear&facet.field=datacentre_facet&facet.field=resourceType_facet&facet.field=schema_version&facet.field=minted&facet.limit=15&facet.mincount=1&facet.range=minted&f.minted.facet.range.start=2004-01-01T00%3A00%3A00Z&f.minted.facet.range.end=2024-01-01T00%3A00%3A00Z&f.minted.facet.range.gap=%2B1YEAR&sort=minted+desc&defType=edismax&bq=updated%3A%5BNOW%2FDAY-1YEAR+TO+NOW%2FDAY%5D&wt=json

so its ok; no difference whatsoever

**Comment by richardhallett** [comment]
LGTM
