### ISSUE TITLE
/works/<doi> does not return metadata about the DOI I queried

### ISSUE THREAD

**Issue by sfisher** [datacite/spinone#43]
The documentation at https://support.datacite.org/docs/api says I can retrieve *singleton* information about a specific identifier I'd like information about with examples like:

```
curl https://api.datacite.org/works/10.5438/0012
```

When I try it with certain identifiers I actually get a different record than what I requested.

For example:

```
curl https://api.datacite.org/works/10.1098/rsif.2017.0030 # returns information about https://doi.org/10.6084/m9.figshare.c.3706801
curl https://api.datacite.org/works/10.1126/sciadv.1602232 # returns information about https://doi.org/10.6071/m3rp49
curl https://api.datacite.org/works/10.1021/acs.jctc.6b00449 # returns information about https://doi.org/10.7280/d1s887
```

**Comment by mfenner** [comment]
Related: https://github.com/datacite/bolognese/issues/28
